//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BanorteBDEntities : DbContext
    {
        public BanorteBDEntities()
            : base("name=BanorteBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
    
        public virtual ObjectResult<SP_GetEmpleados_Result> SP_GetEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmpleados_Result>("SP_GetEmpleados");
        }
    
        public virtual ObjectResult<SP_GetEmpleadosByPage_Result> SP_GetEmpleadosByPage(Nullable<int> iNDEXPAGE)
        {
            var iNDEXPAGEParameter = iNDEXPAGE.HasValue ?
                new ObjectParameter("INDEXPAGE", iNDEXPAGE) :
                new ObjectParameter("INDEXPAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmpleadosByPage_Result>("SP_GetEmpleadosByPage", iNDEXPAGEParameter);
        }
    }
}
