//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public long idEmpleado { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public int edad { get; set; }
        public string telefono { get; set; }
        public string sexo { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public decimal salario { get; set; }
        public int sucursal { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Sucursales Sucursales { get; set; }
    }
}
