//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public int edad { get; set; }
        public string telefono { get; set; }
        public string sexo { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public decimal salario { get; set; }
        public int sucursal { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Sucursales Sucursales { get; set; }
    }
}
